# Generated by Django 3.2.13 on 2022-06-16 11:18

import autoslug.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_list', models.CharField(max_length=100)),
                ('time_create', models.DateField(auto_now_add=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name_list')),
                ('user_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Список покупок',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy', models.CharField(max_length=150)),
                ('time_create', models.DateField(auto_now_add=True)),
                ('check', models.BooleanField()),
                ('list_name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Список покупок',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('time_create', models.DateField(auto_now_add=True)),
                ('time_deadline', models.DateField(default=datetime.date.today)),
                ('check', models.BooleanField()),
                ('user_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Список дел',
                'ordering': ['time_deadline'],
            },
        ),
    ]
